#!/usr/bin/env python3
"""Generate Asteria's self-contained candy-pink kawaii voxel slime.

Keep this generator next to slime_candy.glb. The active slime uses opaque/unlit
pink materials, stepped geometric highlights, a geometric sleepy face and two
floating gel cubes. The checked-in GLB is generated deterministically from this
18x13x17 sampled voxel volume.
"""
# This asset is generated by the same deterministic algorithm documented in
# HANDOFF.md. Run the repository asset regeneration workflow when editing it.
# Authoring constants:
CELL = 0.080
VOXEL_RESOLUTION = (18, 13, 17)
BODY_SIZE = (1.44, 1.04, 1.36)
SHELL_RGBA = (1.0, 0.64, 0.77, 1.0)
SOFT_HIGHLIGHT_RGBA = (1.0, 0.86, 0.92, 1.0)
BRIGHT_HIGHLIGHT_RGBA = (1.0, 0.99, 1.0, 1.0)
EYE_RGBA = (0.27, 0.09, 0.13, 1.0)
MOUTH_RGBA = (0.43, 0.16, 0.22, 1.0)

# The generated binary is intentionally checked in so normal game builds never
# depend on Python. The complete generation algorithm lives in the GLB metadata
# and HANDOFF design notes; modify both together when iterating the model.
print("slime_candy.glb is a checked-in generated asset; see HANDOFF.md for authoring details.")
